In [ ]:
import requests
import pandas as pd
import numpy as np
import json
import janitor
import math
import time
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import duckdb
from scipy import stats

### research questions
* is there a specific month with the lowest & highest transactions? 

#### Considerations
* remaining lease must be more than 60 years. anything less means pro-rated HDB loans, less than 20 years no HDB loans
* remaining lease must be more than 40 for bank loans, anything less than 30 no bank loans.

In [8]:
def setmyplotstyle():
    #plt.style.use('fivethirtyeight')
    plt.style.use('seaborn-v0_8-pastel')
    #plt.style.use('dark_background')
    plt.rcParams['figure.figsize'] = (22, 8)
    plt.rcParams['font.size'] = 14
    #plt.rcParams['font.family'] = 'sans-serif'
    #plt.rcParams['font.sans-serif'] = 'Helvetica'
    plt.rcParams['axes.facecolor'] = 'white'
    plt.rcParams['figure.facecolor'] = 'white'
    plt.rcParams['axes.grid'] = False
    plt.rcParams['axes.spines.right'] = False
    plt.rcParams['axes.spines.top'] = False
    plt.rcParams['axes.edgecolor'] = 'black'
    plt.rcParams['axes.linewidth'] = 0.8
    plt.rcParams['lines.linewidth'] = 1.5
    plt.rcParams['figure.titleweight'] = 'bold'
setmyplotstyle()

def format_float(value):
    return f'{value:,.2f}'
pd.options.display.float_format = format_float

In [9]:
# function to download file directly from data.gov website
def download_file(DATASET_ID):
  s = requests.Session()

  initiate_download_response = s.get(
      f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/initiate-download",
      headers={"Content-Type":"application/json"},
      json={}
  )
  print(initiate_download_response.json()['data']['message'])

  # poll download
  MAX_POLLS = 5
  for i in range(MAX_POLLS):
    poll_download_response = s.get(
        f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/poll-download",
        headers={"Content-Type":"application/json"},
        json={}
    )
    print("Poll download response:", poll_download_response.json())
    if "url" in poll_download_response.json()['data']:
      print(poll_download_response.json()['data']['url'])
      DOWNLOAD_URL = poll_download_response.json()['data']['url']
      df = pd.read_csv(DOWNLOAD_URL)
      df.to_parquet("hdb_downloaded.parquet",index=False)
      #display(df.head())
      print("\nDataframe loaded!")
      return df
    if i == MAX_POLLS - 1:
      print(f"{i+1}/{MAX_POLLS}: No result found, possible error with dataset, please try again or let us know at https://go.gov.sg/datagov-supportform\n")
    else:
      print(f"{i+1}/{MAX_POLLS}: No result yet, continuing to poll\n")
    time.sleep(3)

df = download_file('d_8b84c4ee58e3cfc0ece0d773c8ca6abc')

Download successfully initiated. Proceed to poll download
Poll download response: {'code': 0, 'data': {'status': 'DOWNLOAD_SUCCESS', 'url': 'https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/6f8109f7bce05c219b3825a999cc7f3a02cbc19fe536138a5eaf86bfe6d8711f.csv?AWSAccessKeyId=ASIAU7LWPY2WKMLFZNDH&Expires=1756741844&Signature=dY7m3aAkM5Mfo7FCeZv%2FummbM58%3D&X-Amzn-Trace-Id=Root%3D1-68b5b2c3-5df7377d540294fa5b483852%3BParent%3Dddfc79fd3a4e504d%3BSampled%3D0%3BLineage%3D1%3Affb76583%3A0&response-content-disposition=attachment%3B%20filename%3D%22ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv%22&x-amz-security-token=IQoJb3JpZ2luX2VjEK%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkcwRQIgFHrbGMk1XT5KWMt5LcdPrq6dMKT9xIvSCiT8szU9W9cCIQDOoOTkJPbefC6bM0gRdKr22zlOWJ8VMVtQDxkLvEmupSqqAwgYEAQaDDM0MjIzNTI2ODc4MCIMfbdnBxGiikYugpLfKocDudeGxOXIvDJmZ23XIcDFxxMVkbipJZCS7isc0ug1FURO2%2FZ2bEnoVGZbc1%2FJoqH4m06gE4EsABb8esozeckGeUYYvBufJx5HhkukHGleLgbQt3e4klI8loZZ2mzXHUHw77nJ%2F%2BDCrJxMmWaEy2TZP3G5ircSZFQH6c%2FUXIk66Nh%2BYI1E2kKgXb9zLE%2FAvLzLdfDSM8J7KXRFFK3QUj5z5gqHtM%2BjX9vI8sw1N6vQpsJTukntiaFmjZ7uTmo2mhPVpQ85zGFR61fI7NPeuWLY8JuBIbOxnoA6Xbxn2obp7mrcz1sl26YxjVEkW%2FNEalLK%2BTH62sL5xp9mHYc886WZj3KOqQtVjflL4qhpkqFD4rrZ%2FVB5AIOkJ8dkzD6C4%2FrWUnW1HYvSFZtpPydNTY%2BvL0xrhLu%2BEuYfKFoSwPfN3SHfirP2JZNZ%2BRPtv%2Fj0Pw0q%2Ft%2BrkhRexbruktPk3Abk%2BWKcsBpa%2Bpqr7wKDei1FwbQRtAlvaYHmZMNZWjhYas1IDBq%2Bao2bXjCY4dbFBjqdASmb4mijswGHiKPi3Q6MY43RzoNwcm5G3GOQDGn9RkarhxxAQSRvsKKZNX7V6aWBTOISYM52%2FZFE4WDAnfiVpqUKKIwOuIFffYyH7vyeMCeoSIGxQeUX00EfhJwkhaOskcuuRT8Cygzt6Wz4EgYfTWV%2Fw3xoO7JUX%2Bwu%2B5gyr8SZ57MCI3w2Tb3%2Fx5xt7trCIQflVSgw6DWI%2FmPbY1Y%3D'}, 'errorMsg': ''}
https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/6f8109f7bce05c219b3825a999cc7f3a02cbc19fe536138a5eaf86bfe6d8711f.csv?AWSAccessKeyId=ASIAU7LWPY2WKMLFZNDH&Expires=1756741844&Signature=dY7m3aAkM5Mfo7FCeZv%2FummbM58%3D&X-Amzn-Trace-Id=Root%3D1-68b5b2c3-5df7377d540294fa5b483852%3BParent%3Dddfc79fd3a4e504d%3BSampled%3D0%3BLineage%3D1%3Affb76583%3A0&response-content-disposition=attachment%3B%20filename%3D%22ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv%22&x-amz-security-token=IQoJb3JpZ2luX2VjEK%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkcwRQIgFHrbGMk1XT5KWMt5LcdPrq6dMKT9xIvSCiT8szU9W9cCIQDOoOTkJPbefC6bM0gRdKr22zlOWJ8VMVtQDxkLvEmupSqqAwgYEAQaDDM0MjIzNTI2ODc4MCIMfbdnBxGiikYugpLfKocDudeGxOXIvDJmZ23XIcDFxxMVkbipJZCS7isc0ug1FURO2%2FZ2bEnoVGZbc1%2FJoqH4m06gE4EsABb8esozeckGeUYYvBufJx5HhkukHGleLgbQt3e4klI8loZZ2mzXHUHw77nJ%2F%2BDCrJxMmWaEy2TZP3G5ircSZFQH6c%2FUXIk66Nh%2BYI1E2kKgXb9zLE%2FAvLzLdfDSM8J7KXRFFK3QUj5z5gqHtM%2BjX9vI8sw1N6vQpsJTukntiaFmjZ7uTmo2mhPVpQ85zGFR61fI7NPeuWLY8JuBIbOxnoA6Xbxn2obp7mrcz1sl26YxjVEkW%2FNEalLK%2BTH62sL5xp9mHYc886WZj3KOqQtVjflL4qhpkqFD4rrZ%2FVB5AIOkJ8dkzD6C4%2FrWUnW1HYvSFZtpPydNTY%2BvL0xrhLu%2BEuYfKFoSwPfN3SHfirP2JZNZ%2BRPtv%2Fj0Pw0q%2Ft%2BrkhRexbruktPk3Abk%2BWKcsBpa%2Bpqr7wKDei1FwbQRtAlvaYHmZMNZWjhYas1IDBq%2Bao2bXjCY4dbFBjqdASmb4mijswGHiKPi3Q6MY43RzoNwcm5G3GOQDGn9RkarhxxAQSRvsKKZNX7V6aWBTOISYM52%2FZFE4WDAnfiVpqUKKIwOuIFffYyH7vyeMCeoSIGxQeUX00EfhJwkhaOskcuuRT8Cygzt6Wz4EgYfTWV%2Fw3xoO7JUX%2Bwu%2B5gyr8SZ57MCI3w2Tb3%2Fx5xt7trCIQflVSgw6DWI%2FmPbY1Y%3D

Dataframe loaded!

In [10]:
def transformData(df: pd.DataFrame) -> pd.DataFrame:
    transactions = (
        df.clean_names()
        .convert_dtypes()
        .change_type(['floor_area_sqm','lease_commence_date','resale_price'],dtype=int,ignore_exception='fillna')
        .change_type(['town','flat_type','block','street_name','storey_range','flat_model'],dtype=str)
        .transform_columns(['flat_model'],lambda x: x.upper(),elementwise=True)
        .add_column(column_name='year',value=df['month'].str[0:4])
        .add_column(column_name='mth',value=df['month'].str[5:7])
    )
    transactions['floor_area_sqft'] = transactions['floor_area_sqm'].astype('float')*10.764
    transactions['priceper_sqm'] = transactions['resale_price']/transactions['floor_area_sqm']
    transactions['priceper_sqft'] = transactions['resale_price']/transactions['floor_area_sqft']
    transactions['date'] = '01'+"/"+transactions["mth"]+"/"+transactions["year"]
    transactions['date'] = pd.to_datetime(transactions['date'], format="%d/%m/%Y", errors="coerce")
    
    transactions["split"] = transactions["remaining_lease"].str.split()
    transactions["years"] = transactions["split"].str[0].astype(float).fillna(0).astype(int)
    transactions["months"] = transactions["split"].str[2].astype(float).fillna(0).astype(int)
    transactions["remaining_lease_years"] = transactions["years"] + (transactions["months"]/12)
    # drop excess columns
    transactions = transactions.drop(columns=['split', 'years', 'months'])

    transactions = transactions.change_type(['mth','year'],dtype='int',ignore_exception='keep_values')
    transactions = transactions.sort_values('date')
    
    # save transformed file:
    transactions.to_csv("hdbresale_transactions_transformed.csv", index=False)
    
    return transactions

r = transformData(df)
r.info()

/opt/homebrew/Caskroom/miniforge/base/envs/py312/lib/python3.12/site-packages/pandas_flavor/register.py:164: FutureWarning:

This function will be deprecated in a 1.x release. Please use `pd.DataFrame.astype` instead.

/opt/homebrew/Caskroom/miniforge/base/envs/py312/lib/python3.12/site-packages/pandas_flavor/register.py:164: FutureWarning:

This function will be deprecated in a 1.x release. Please use `pd.DataFrame.astype` instead.

/opt/homebrew/Caskroom/miniforge/base/envs/py312/lib/python3.12/site-packages/pandas_flavor/register.py:164: FutureWarning:

This function will be deprecated in a 1.x release. Please use `pd.DataFrame.assign` instead.

/opt/homebrew/Caskroom/miniforge/base/envs/py312/lib/python3.12/site-packages/pandas_flavor/register.py:164: FutureWarning:

This function will be deprecated in a 1.x release. Please use `pd.DataFrame.assign` instead.

/opt/homebrew/Caskroom/miniforge/base/envs/py312/lib/python3.12/site-packages/pandas_flavor/register.py:164: FutureWarning:

This function will be deprecated in a 1.x release. Please use `pd.DataFrame.astype` instead.

<class 'pandas.core.frame.DataFrame'>
Index: 214893 entries, 0 to 199621
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   month                  214893 non-null  string
 1   town                   214893 non-null  object
 2   flat_type              214893 non-null  object
 3   block                  214893 non-null  object
 4   street_name            214893 non-null  object
 5   storey_range           214893 non-null  object
 6   floor_area_sqm         214893 non-null  int64
 7   flat_model             214893 non-null  object
 8   lease_commence_date    214893 non-null  int64
 9   remaining_lease        214893 non-null  string
 10  resale_price           214893 non-null  int64
 11  year                   214893 non-null  int64
 12  mth                    214893 non-null  int64
 13  floor_area_sqft        214893 non-null  float64
 14  priceper_sqm           214893 non-null  float64
 15  priceper_sqft          214893 non-null  float64
 16  date                   214893 non-null  datetime64[ns]
 17  remaining_lease_years  214893 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(5), object(6), string(2)
memory usage: 31.2+ MB

In [6]:
# archived
# function to slowly iterate and extract data over api with rate limits
def getHDBData() -> pd.DataFrame:
    # get data
    base_url = "https://data.gov.sg/api/action/datastore_search"
    resource_id = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc"
    
    headers = {
        'AccessKey':'32417271-1c2e-4a9f-bd17-f97c6ce79c4e',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0'
    }
    
    all_records = []
    offset = 0
    limit = 100
    total_records = None
    
    while total_records is None or offset < total_records:
        api_url = f"{base_url}?resource_id={resource_id}&offset={offset}"
        response = requests.get(url=api_url, headers=headers)

        if response.status_code == 200:
            data = json.loads(response.text)
            records = data['result']['records']
            all_records.extend(records)
            
            if total_records is None:
                total_records = data['result']['total']
            
            offset += len(records)
            #print(f"Retrieved {offset} out of {total_records} records")
        else:
            print(f"Error: {response.status_code}")
            break
    
    df = pd.DataFrame(all_records)
    return df

def transformData(df: pd.DataFrame) -> pd.DataFrame:
    transactions = (
        df.clean_names()
        .convert_dtypes()
        .change_type(['floor_area_sqm','lease_commence_date','resale_price'],dtype=int,ignore_exception='fillna')
        .change_type(['town','flat_type','block','street_name','storey_range','flat_model'],dtype=str)
        .transform_columns(['flat_model'],lambda x: x.upper(),elementwise=True)
        .add_column(column_name='year',value=df['month'].str[0:4])
        .add_column(column_name='mth',value=df['month'].str[5:7])
    )
    transactions['floor_area_sqft'] = transactions['floor_area_sqm'].astype('float')*10.764
    transactions['priceper_sqm'] = transactions['resale_price']/transactions['floor_area_sqm']
    transactions['priceper_sqft'] = transactions['resale_price']/transactions['floor_area_sqft']
    transactions['date'] = '01'+"/"+transactions["mth"]+"/"+transactions["year"]
    transactions['date'] = pd.to_datetime(transactions['date'], format="%d/%m/%Y", errors="coerce")

    transactions = transactions.change_type(['mth','year'],dtype='int',ignore_exception='keep_values')
    transactions = transactions.sort_values('date')
    return transactions

def getData(refresh: bool = False) -> pd.DataFrame:
    ## if refresh is False, just use already available data, else, get it from API again
    if refresh == False:
        return pd.read_feather('hdb_downloaded.feather')
    else:
        df = getHDBData()
        df_t = transformData(df)
        df_t.to_feather('hdb_downloaded.feather')
        return df_t
        
#r = getData(refresh=True)
#r.to_csv('hdb_downloaded.csv',index=False)

In [ ]:
query = """
SELECT
    town,
    lease_commence_date,
    COUNT(*) AS count
FROM r
WHERE flat_type IN ('4 ROOM')
AND lease_commence_date > 1967 AND floor_area_sqm < 90
GROUP BY town, lease_commence_date
ORDER BY lease_commence_date
"""
df = duckdb.query(query).df()
df

                town  lease_commence_date  count
0        BUKIT MERAH                 1970     59
1         QUEENSTOWN                 1970     27
2            GEYLANG                 1971      5
3    KALLANG/WHAMPOA                 1972     26
4          TOA PAYOH                 1972      3
..               ...                  ...    ...
180      JURONG WEST                 2017     16
181        WOODLANDS                 2017     21
182         CLEMENTI                 2018      7
183      BUKIT MERAH                 2019     28
184       QUEENSTOWN                 2020     19

[185 rows x 3 columns]

In [16]:
query = """
SELECT DISTINCT
    -- flat_model, 
    town
    -- lease_commence_date
FROM r
WHERE flat_type IN ('4 ROOM')
AND lease_commence_date > 1967 AND floor_area_sqm < 90
ORDER BY lease_commence_date
"""
df = duckdb.query(query).df()
df

               town
0        QUEENSTOWN
1     MARINE PARADE
2   KALLANG/WHAMPOA
3         TOA PAYOH
4        ANG MO KIO
5      CENTRAL AREA
6       BUKIT BATOK
7         SERANGOON
8             BEDOK
9            YISHUN
10          HOUGANG
11      JURONG EAST
12           BISHAN
13         TAMPINES
14    BUKIT PANJANG
15      BUKIT TIMAH
16      JURONG WEST
17         SENGKANG
18    CHOA CHU KANG
19        SEMBAWANG
20          PUNGGOL
21          GEYLANG
22         CLEMENTI
23        PASIR RIS
24        WOODLANDS
25      BUKIT MERAH

In [8]:
r.describe()

,floor_area_sqm,lease_commence_date,resale_price,year,mth,floor_area_sqft,priceper_sqm,priceper_sqft,date
count,"210,771.00","210,771.00","210,771.00","210,771.00","210,771.00","210,771.00","210,771.00","210,771.00",210771
mean,96.86,"1,996.34","517,354.64","2,021.01",6.47,"1,042.60","5,397.60",501.45,2021-06-19 14:58:40.116145664
min,31.00,"1,966.00","140,000.00","2,017.00",1.00,333.68,"2,089.55",194.12,2017-01-01 00:00:00
25%,82.00,"1,985.00","380,000.00","2,019.00",4.00,882.65,"4,292.45",398.78,2019-07-01 00:00:00
50%,93.00,"1,996.00","485,000.00","2,021.00",7.00,"1,001.05","5,121.95",475.84,2021-08-01 00:00:00
75%,112.00,"2,011.00","620,000.00","2,023.00",9.00,"1,205.57","6,111.11",567.74,2023-07-01 00:00:00
max,366.00,"2,022.00","1,658,888.00","2,025.00",12.00,"3,939.62","16,148.94","1,500.27",2025-07-01 00:00:00
std,24.03,14.24,"182,658.89",2.42,3.39,258.67,"1,567.18",145.59,NaN

In [9]:
r.town.unique()

array(['ANG MO KIO', 'SEMBAWANG', 'QUEENSTOWN', 'PUNGGOL', 'SENGKANG',
       'KALLANG/WHAMPOA', 'JURONG WEST', 'MARINE PARADE', 'PASIR RIS',
       'WOODLANDS', 'YISHUN', 'TAMPINES', 'SERANGOON', 'TOA PAYOH',
       'BUKIT MERAH', 'BUKIT BATOK', 'BUKIT PANJANG', 'BISHAN', 'BEDOK',
       'BUKIT TIMAH', 'JURONG EAST', 'HOUGANG', 'CHOA CHU KANG',
       'CLEMENTI', 'CENTRAL AREA', 'GEYLANG'], dtype=object)

In [10]:
r.flat_type.unique()

array(['2 ROOM', '4 ROOM', '5 ROOM', '3 ROOM', 'EXECUTIVE', '1 ROOM',
       'MULTI-GENERATION'], dtype=object)

In [11]:
r.flat_model.unique()

array(['IMPROVED', 'MODEL A2', 'STANDARD', 'MODEL A', 'APARTMENT',
       'PREMIUM APARTMENT', 'NEW GENERATION', 'SIMPLIFIED', 'DBSS',
       'MAISONETTE', 'ADJOINED FLAT', 'MODEL A-MAISONETTE', 'TYPE S2',
       'TYPE S1', 'TERRACE', 'IMPROVED-MAISONETTE', 'PREMIUM MAISONETTE',
       'MULTI GENERATION', 'PREMIUM APARTMENT LOFT', '2-ROOM', '3GEN'],
      dtype=object)

In [5]:
#d_ignorelist = [7,8,17,18,22,19,25,26,27]
#base_query = ' propertytype != "executive condominium" & year >= 23 & (sqft >= 517 & sqft < 1000 ) & pricepersqft <=2000 '
#g4 = transactions.query(f'district not in @d_ignorelist & typeofsale == 2 & {base_query}',engine='python')\
#flat_ignore = ['1 ROOM','2 ROOM']
#town = ['CENTRAL AREA']
year = [2024,2025]
flat = ["4 ROOM"]
base_query = ' flat_type in @flat & year in @year '
g4 = r.query(f'{base_query} & lease_commence_date > 1977',engine='python')\
    .groupby(['month'])\
    .agg(
    _count=('flat_model','size'),
    _mean_resaleprice=('resale_price','mean'),
    _min_resaleprice=('resale_price','min'),
    _max_resaleprice=('resale_price','max'),
    _minprice_sqft=('priceper_sqft','min'),
    _meanprice_sqft=('priceper_sqft','mean'),
    _medianprice_sqft=('priceper_sqft','median'),
    _maxprice_sqft=('priceper_sqft','max'),
    _minsqft=('floor_area_sqft','min'),
    _maxsqft=('floor_area_sqft','max')
).sort_values(by='_mean_resaleprice')
display(g4)

,_count,_mean_resaleprice,_min_resaleprice,_max_resaleprice,_minprice_sqft,_meanprice_sqft,_medianprice_sqft,_maxprice_sqft,_minsqft,_maxsqft
month,,,,,,,,,,
2024-01,1129,"600,620.77",392000,1200000,360.79,589.85,554.63,"1,173.50",807.30,"1,431.61"
2024-02,876,"601,737.24",400000,1158000,387.77,589.98,554.16,"1,208.85",807.30,"1,323.97"
2024-04,1010,"607,620.62",400000,1238000,364.32,595.39,556.41,"1,168.77",818.06,"1,323.97"
2024-03,836,"614,310.64",417000,1370000,388.05,602.89,565.49,"1,320.19",807.30,"1,248.62"
2024-05,1012,"617,456.81",415000,1450000,385.00,606.85,569.57,"1,448.48",861.12,"1,259.39"
2024-08,1060,"631,895.09",420000,1380000,399.57,622.56,583.91,"1,349.53",882.65,"1,291.68"
2024-06,888,"639,257.91",400000,1365000,367.19,628.69,583.16,"1,349.06",807.30,"1,227.10"
2024-07,1328,"641,046.84",418000,1400000,387.84,631.88,587.15,"1,369.09",818.06,"1,431.61"
2024-11,822,"643,779.51",438000,1302000,404.85,632.10,591.72,"1,300.63",818.06,"1,237.86"
2024-09,894,"653,578.14",420000,1408000,378.82,642.05,599.37,"1,391.56",807.30,"1,280.92"
2024-10,868,"656,797.41",432000,1388888,409.53,647.27,611.94,"1,387.43",818.06,"1,259.39"
2025-01,998,"663,702.28",445000,1400000,417.63,654.48,606.72,"1,398.53",807.30,"1,248.62"
2024-12,926,"665,966.41",450000,1430000,412.42,653.44,610.89,"1,413.30",807.30,"1,270.15"
2025-02,841,"668,741.74",430000,1338000,396.86,654.32,610.50,"1,351.12",818.06,"1,453.14"
2025-07,1100,"673,703.12",450000,1420000,424.31,662.29,614.35,"1,388.64",807.30,"1,248.62"
2025-03,790,"674,416.10",445000,1518000,401.98,665.76,619.35,"1,500.27",807.30,"1,313.21"
2025-05,965,"675,209.87",420000,1430000,412.90,663.91,621.35,"1,414.20",807.30,"1,259.39"
2025-08,944,"675,539.19",450000,1425000,408.34,663.78,619.35,"1,423.50",807.30,"1,323.97"
2025-04,971,"677,262.52",300000,1388888,331.79,665.57,624.34,"1,378.55",807.30,"1,259.39"
2025-06,913,"682,111.05",432888,1423888,423.76,668.31,619.35,"1,377.94",807.30,"1,323.97"

In [6]:
fig = px.bar(g4, y=["_min_resaleprice","_max_resaleprice"], text_auto=True,title='mean resale price: hdb resale from 2024 to date')
fig.update_layout(barmode='group')
fig.show()

In [ ]:
pdata.query(f' typeofsale == 2 & {base_query}',engine='python')\
    .groupby(['project'])\
    .agg(
    _count=('noofunits',np.sum),
    _minprice_sqft=('pricepersqft',np.min),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max),
    _minsqft=('sqft',np.min),
    _maxsqft=('sqft',np.max)
).sort_values(by='_maxprice_sqft')

In [ ]:
g1 = pdata.query('project.str.contains("euhabitat") & area==49',engine='python').groupby(['_date','area','floorrange']).agg(
    _count=('noofunits',np.sum),
    _minprice_sqft=('pricepersqft',np.min),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max)
).sort_values(by='_date',ascending=False)
g1

In [ ]:
g1 = pdata.query('district==15 & area==49 & year>=20',engine='python').groupby(['_date','project']).agg(
    _count=('noofunits',np.sum),
    _minprice_sqft=('pricepersqft',np.min),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max)
).sort_values(by='_date',ascending=False)
g1

In [ ]:
pdata.query("typeofsale==1 & area==46").groupby(['marketsegment','_date']).agg(
    _count=('noofunits',np.sum),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max)
)

In [ ]:
pdata.query('project.str.contains("euhabitat") & sqft==527 & year>=18').groupby(['floorrange','sqft','_date','typeofsale']).agg(
    _count=('noofunits',np.sum),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max)
)._maxprice_sqft.plot.bar()

In [ ]:
g1 = pdata.query('project.str.contains("euhabitat") & sqft==527 & year>=18').groupby(['_date']).agg(
    _count=('noofunits',np.sum),
    _meanprice_sqft=('pricepersqft',np.mean),
    _maxprice_sqft=('pricepersqft',np.max),
    _maxgrossprice=('price',np.max)
)#._maxprice_sqft.plot.bar()

In [ ]:
fig = px.bar(g1, y="_meanprice_sqft", text_auto=True)
fig.show()